server:
  port: 8888
spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CKANYWHERE/study-spring-cloud-config
          default-label: main
          #uri: git repo
          #username: [username]
          #password: [password]
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
