server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CKANYWHERE/study-spring-cloud-config
          default-label: main
          #uri: git repo
          #username: [username]
          #password: [password]

